// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.17.3
// source: plugin.proto

package protobuff

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Plugin category enum (renamed from PluginType)
type PluginCategory int32

const (
	PluginCategory_PLUGIN_CATEGORY_NORMAL   PluginCategory = 0 // auth, customFunction etc
	PluginCategory_PLUGIN_CATEGORY_FUNCTION PluginCategory = 1 // function execution plugins
	PluginCategory_PLUGIN_CATEGORY_STORAGE  PluginCategory = 2 // s3, cloudinary etc
)

// Enum value maps for PluginCategory.
var (
	PluginCategory_name = map[int32]string{
		0: "PLUGIN_CATEGORY_NORMAL",
		1: "PLUGIN_CATEGORY_FUNCTION",
		2: "PLUGIN_CATEGORY_STORAGE",
	}
	PluginCategory_value = map[string]int32{
		"PLUGIN_CATEGORY_NORMAL":   0,
		"PLUGIN_CATEGORY_FUNCTION": 1,
		"PLUGIN_CATEGORY_STORAGE":  2,
	}
)

func (x PluginCategory) Enum() *PluginCategory {
	p := new(PluginCategory)
	*p = x
	return p
}

func (x PluginCategory) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PluginCategory) Descriptor() protoreflect.EnumDescriptor {
	return file_plugin_proto_enumTypes[0].Descriptor()
}

func (PluginCategory) Type() protoreflect.EnumType {
	return &file_plugin_proto_enumTypes[0]
}

func (x PluginCategory) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PluginCategory.Descriptor instead.
func (PluginCategory) EnumDescriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{0}
}

// Plugin type enum for internal vs external
type PluginType int32

const (
	PluginType_PLUGIN_TYPE_INTERNAL PluginType = 0 // System-wide plugins (registered to system API)
	PluginType_PLUGIN_TYPE_EXTERNAL PluginType = 1 // Project-specific plugins
)

// Enum value maps for PluginType.
var (
	PluginType_name = map[int32]string{
		0: "PLUGIN_TYPE_INTERNAL",
		1: "PLUGIN_TYPE_EXTERNAL",
	}
	PluginType_value = map[string]int32{
		"PLUGIN_TYPE_INTERNAL": 0,
		"PLUGIN_TYPE_EXTERNAL": 1,
	}
)

func (x PluginType) Enum() *PluginType {
	p := new(PluginType)
	*p = x
	return p
}

func (x PluginType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PluginType) Descriptor() protoreflect.EnumDescriptor {
	return file_plugin_proto_enumTypes[1].Descriptor()
}

func (PluginType) Type() protoreflect.EnumType {
	return &file_plugin_proto_enumTypes[1]
}

func (x PluginType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PluginType.Descriptor instead.
func (PluginType) EnumDescriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{1}
}

// Plugin load status
type PluginLoadStatus int32

const (
	PluginLoadStatus_PLUGIN_LOAD_STATUS_NOT_INSTALLED PluginLoadStatus = 0
	PluginLoadStatus_PLUGIN_LOAD_STATUS_INSTALLED     PluginLoadStatus = 1
	PluginLoadStatus_PLUGIN_LOAD_STATUS_REINSTALL     PluginLoadStatus = 2
	PluginLoadStatus_PLUGIN_LOAD_STATUS_LOADING       PluginLoadStatus = 3
	PluginLoadStatus_PLUGIN_LOAD_STATUS_LOADED        PluginLoadStatus = 4
	PluginLoadStatus_PLUGIN_LOAD_STATUS_LOAD_FAILED   PluginLoadStatus = 5
)

// Enum value maps for PluginLoadStatus.
var (
	PluginLoadStatus_name = map[int32]string{
		0: "PLUGIN_LOAD_STATUS_NOT_INSTALLED",
		1: "PLUGIN_LOAD_STATUS_INSTALLED",
		2: "PLUGIN_LOAD_STATUS_REINSTALL",
		3: "PLUGIN_LOAD_STATUS_LOADING",
		4: "PLUGIN_LOAD_STATUS_LOADED",
		5: "PLUGIN_LOAD_STATUS_LOAD_FAILED",
	}
	PluginLoadStatus_value = map[string]int32{
		"PLUGIN_LOAD_STATUS_NOT_INSTALLED": 0,
		"PLUGIN_LOAD_STATUS_INSTALLED":     1,
		"PLUGIN_LOAD_STATUS_REINSTALL":     2,
		"PLUGIN_LOAD_STATUS_LOADING":       3,
		"PLUGIN_LOAD_STATUS_LOADED":        4,
		"PLUGIN_LOAD_STATUS_LOAD_FAILED":   5,
	}
)

func (x PluginLoadStatus) Enum() *PluginLoadStatus {
	p := new(PluginLoadStatus)
	*p = x
	return p
}

func (x PluginLoadStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PluginLoadStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_plugin_proto_enumTypes[2].Descriptor()
}

func (PluginLoadStatus) Type() protoreflect.EnumType {
	return &file_plugin_proto_enumTypes[2]
}

func (x PluginLoadStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PluginLoadStatus.Descriptor instead.
func (PluginLoadStatus) EnumDescriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{2}
}

// Plugin activate status
type PluginActivateStatus int32

const (
	PluginActivateStatus_PLUGIN_ACTIVATE_STATUS_DEACTIVATED PluginActivateStatus = 0
	PluginActivateStatus_PLUGIN_ACTIVATE_STATUS_ACTIVATED   PluginActivateStatus = 1
)

// Enum value maps for PluginActivateStatus.
var (
	PluginActivateStatus_name = map[int32]string{
		0: "PLUGIN_ACTIVATE_STATUS_DEACTIVATED",
		1: "PLUGIN_ACTIVATE_STATUS_ACTIVATED",
	}
	PluginActivateStatus_value = map[string]int32{
		"PLUGIN_ACTIVATE_STATUS_DEACTIVATED": 0,
		"PLUGIN_ACTIVATE_STATUS_ACTIVATED":   1,
	}
)

func (x PluginActivateStatus) Enum() *PluginActivateStatus {
	p := new(PluginActivateStatus)
	*p = x
	return p
}

func (x PluginActivateStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PluginActivateStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_plugin_proto_enumTypes[3].Descriptor()
}

func (PluginActivateStatus) Type() protoreflect.EnumType {
	return &file_plugin_proto_enumTypes[3]
}

func (x PluginActivateStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PluginActivateStatus.Descriptor instead.
func (PluginActivateStatus) EnumDescriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{3}
}

type PluginLanguage int32

const (
	PluginLanguage_PLUGIN_LANGUAGE_GO         PluginLanguage = 0
	PluginLanguage_PLUGIN_LANGUAGE_JS         PluginLanguage = 1
	PluginLanguage_PLUGIN_LANGUAGE_CPP        PluginLanguage = 2
	PluginLanguage_PLUGIN_LANGUAGE_PYTHON     PluginLanguage = 3
	PluginLanguage_PLUGIN_LANGUAGE_JAVA       PluginLanguage = 4
	PluginLanguage_PLUGIN_LANGUAGE_RUBY       PluginLanguage = 5
	PluginLanguage_PLUGIN_LANGUAGE_PHP        PluginLanguage = 6
	PluginLanguage_PLUGIN_LANGUAGE_CSHARP     PluginLanguage = 7
	PluginLanguage_PLUGIN_LANGUAGE_TYPESCRIPT PluginLanguage = 8
	PluginLanguage_PLUGIN_LANGUAGE_RUST       PluginLanguage = 9
	PluginLanguage_PLUGIN_LANGUAGE_LUA        PluginLanguage = 10
	PluginLanguage_PLUGIN_LANGUAGE_DART       PluginLanguage = 11
)

// Enum value maps for PluginLanguage.
var (
	PluginLanguage_name = map[int32]string{
		0:  "PLUGIN_LANGUAGE_GO",
		1:  "PLUGIN_LANGUAGE_JS",
		2:  "PLUGIN_LANGUAGE_CPP",
		3:  "PLUGIN_LANGUAGE_PYTHON",
		4:  "PLUGIN_LANGUAGE_JAVA",
		5:  "PLUGIN_LANGUAGE_RUBY",
		6:  "PLUGIN_LANGUAGE_PHP",
		7:  "PLUGIN_LANGUAGE_CSHARP",
		8:  "PLUGIN_LANGUAGE_TYPESCRIPT",
		9:  "PLUGIN_LANGUAGE_RUST",
		10: "PLUGIN_LANGUAGE_LUA",
		11: "PLUGIN_LANGUAGE_DART",
	}
	PluginLanguage_value = map[string]int32{
		"PLUGIN_LANGUAGE_GO":         0,
		"PLUGIN_LANGUAGE_JS":         1,
		"PLUGIN_LANGUAGE_CPP":        2,
		"PLUGIN_LANGUAGE_PYTHON":     3,
		"PLUGIN_LANGUAGE_JAVA":       4,
		"PLUGIN_LANGUAGE_RUBY":       5,
		"PLUGIN_LANGUAGE_PHP":        6,
		"PLUGIN_LANGUAGE_CSHARP":     7,
		"PLUGIN_LANGUAGE_TYPESCRIPT": 8,
		"PLUGIN_LANGUAGE_RUST":       9,
		"PLUGIN_LANGUAGE_LUA":        10,
		"PLUGIN_LANGUAGE_DART":       11,
	}
)

func (x PluginLanguage) Enum() *PluginLanguage {
	p := new(PluginLanguage)
	*p = x
	return p
}

func (x PluginLanguage) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PluginLanguage) Descriptor() protoreflect.EnumDescriptor {
	return file_plugin_proto_enumTypes[4].Descriptor()
}

func (PluginLanguage) Type() protoreflect.EnumType {
	return &file_plugin_proto_enumTypes[4]
}

func (x PluginLanguage) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PluginLanguage.Descriptor instead.
func (PluginLanguage) EnumDescriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{4}
}

// Common types
type EnvVariable struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Hide          bool                   `protobuf:"varint,3,opt,name=hide,proto3" json:"hide,omitempty"`
	IsSystem      bool                   `protobuf:"varint,4,opt,name=is_system,json=isSystem,proto3" json:"is_system,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnvVariable) Reset() {
	*x = EnvVariable{}
	mi := &file_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvVariable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvVariable) ProtoMessage() {}

func (x *EnvVariable) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvVariable.ProtoReflect.Descriptor instead.
func (*EnvVariable) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *EnvVariable) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *EnvVariable) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *EnvVariable) GetHide() bool {
	if x != nil {
		return x.Hide
	}
	return false
}

func (x *EnvVariable) GetIsSystem() bool {
	if x != nil {
		return x.IsSystem
	}
	return false
}

// HashiCorp handshake configuration
type HashiCorpHandshakeConfig struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion  uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	MagicCookieKey   string                 `protobuf:"bytes,2,opt,name=magic_cookie_key,json=magicCookieKey,proto3" json:"magic_cookie_key,omitempty"`
	MagicCookieValue string                 `protobuf:"bytes,3,opt,name=magic_cookie_value,json=magicCookieValue,proto3" json:"magic_cookie_value,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HashiCorpHandshakeConfig) Reset() {
	*x = HashiCorpHandshakeConfig{}
	mi := &file_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HashiCorpHandshakeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HashiCorpHandshakeConfig) ProtoMessage() {}

func (x *HashiCorpHandshakeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HashiCorpHandshakeConfig.ProtoReflect.Descriptor instead.
func (*HashiCorpHandshakeConfig) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *HashiCorpHandshakeConfig) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *HashiCorpHandshakeConfig) GetMagicCookieKey() string {
	if x != nil {
		return x.MagicCookieKey
	}
	return ""
}

func (x *HashiCorpHandshakeConfig) GetMagicCookieValue() string {
	if x != nil {
		return x.MagicCookieValue
	}
	return ""
}

// Plugin details message
type PluginDetails struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title             string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Icon              string                 `protobuf:"bytes,3,opt,name=icon,proto3" json:"icon,omitempty"`
	Serial            int64                  `protobuf:"varint,4,opt,name=serial,proto3" json:"serial,omitempty"`
	Version           string                 `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	Description       string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Category          PluginCategory         `protobuf:"varint,7,opt,name=category,proto3,enum=apito.plugin.v1.PluginCategory" json:"category,omitempty"` // storage, function, normal
	Type              PluginType             `protobuf:"varint,8,opt,name=type,proto3,enum=apito.plugin.v1.PluginType" json:"type,omitempty"`             // New field: internal vs external
	Role              string                 `protobuf:"bytes,9,opt,name=role,proto3" json:"role,omitempty"`
	EnvVars           []*EnvVariable         `protobuf:"bytes,10,rep,name=env_vars,json=envVars,proto3" json:"env_vars,omitempty"`
	ExportedVariable  string                 `protobuf:"bytes,11,opt,name=exported_variable,json=exportedVariable,proto3" json:"exported_variable,omitempty"`
	Enable            bool                   `protobuf:"varint,12,opt,name=enable,proto3" json:"enable,omitempty"`
	Debug             bool                   `protobuf:"varint,13,opt,name=debug,proto3" json:"debug,omitempty"`
	RepositoryUrl     string                 `protobuf:"bytes,14,opt,name=repository_url,json=repositoryUrl,proto3" json:"repository_url,omitempty"`
	Branch            string                 `protobuf:"bytes,15,opt,name=branch,proto3" json:"branch,omitempty"`
	Author            string                 `protobuf:"bytes,16,opt,name=author,proto3" json:"author,omitempty"`
	LoadStatus        PluginLoadStatus       `protobuf:"varint,17,opt,name=load_status,json=loadStatus,proto3,enum=apito.plugin.v1.PluginLoadStatus" json:"load_status,omitempty"`
	ActivateStatus    PluginActivateStatus   `protobuf:"varint,18,opt,name=activate_status,json=activateStatus,proto3,enum=apito.plugin.v1.PluginActivateStatus" json:"activate_status,omitempty"`
	BelongsToProjects []string               `protobuf:"bytes,19,rep,name=belongs_to_projects,json=belongsToProjects,proto3" json:"belongs_to_projects,omitempty"` // project ids
	// HashiCorp specific fields
	BinaryPath      string                    `protobuf:"bytes,20,opt,name=binary_path,json=binaryPath,proto3" json:"binary_path,omitempty"`
	HandshakeConfig *HashiCorpHandshakeConfig `protobuf:"bytes,21,opt,name=handshake_config,json=handshakeConfig,proto3" json:"handshake_config,omitempty"`
	Language        PluginLanguage            `protobuf:"varint,22,opt,name=language,proto3,enum=apito.plugin.v1.PluginLanguage" json:"language,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PluginDetails) Reset() {
	*x = PluginDetails{}
	mi := &file_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginDetails) ProtoMessage() {}

func (x *PluginDetails) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginDetails.ProtoReflect.Descriptor instead.
func (*PluginDetails) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *PluginDetails) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PluginDetails) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PluginDetails) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *PluginDetails) GetSerial() int64 {
	if x != nil {
		return x.Serial
	}
	return 0
}

func (x *PluginDetails) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PluginDetails) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PluginDetails) GetCategory() PluginCategory {
	if x != nil {
		return x.Category
	}
	return PluginCategory_PLUGIN_CATEGORY_NORMAL
}

func (x *PluginDetails) GetType() PluginType {
	if x != nil {
		return x.Type
	}
	return PluginType_PLUGIN_TYPE_INTERNAL
}

func (x *PluginDetails) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *PluginDetails) GetEnvVars() []*EnvVariable {
	if x != nil {
		return x.EnvVars
	}
	return nil
}

func (x *PluginDetails) GetExportedVariable() string {
	if x != nil {
		return x.ExportedVariable
	}
	return ""
}

func (x *PluginDetails) GetEnable() bool {
	if x != nil {
		return x.Enable
	}
	return false
}

func (x *PluginDetails) GetDebug() bool {
	if x != nil {
		return x.Debug
	}
	return false
}

func (x *PluginDetails) GetRepositoryUrl() string {
	if x != nil {
		return x.RepositoryUrl
	}
	return ""
}

func (x *PluginDetails) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *PluginDetails) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *PluginDetails) GetLoadStatus() PluginLoadStatus {
	if x != nil {
		return x.LoadStatus
	}
	return PluginLoadStatus_PLUGIN_LOAD_STATUS_NOT_INSTALLED
}

func (x *PluginDetails) GetActivateStatus() PluginActivateStatus {
	if x != nil {
		return x.ActivateStatus
	}
	return PluginActivateStatus_PLUGIN_ACTIVATE_STATUS_DEACTIVATED
}

func (x *PluginDetails) GetBelongsToProjects() []string {
	if x != nil {
		return x.BelongsToProjects
	}
	return nil
}

func (x *PluginDetails) GetBinaryPath() string {
	if x != nil {
		return x.BinaryPath
	}
	return ""
}

func (x *PluginDetails) GetHandshakeConfig() *HashiCorpHandshakeConfig {
	if x != nil {
		return x.HandshakeConfig
	}
	return nil
}

func (x *PluginDetails) GetLanguage() PluginLanguage {
	if x != nil {
		return x.Language
	}
	return PluginLanguage_PLUGIN_LANGUAGE_GO
}

type ThirdPartyGraphQLSchemas struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queries       *structpb.Struct       `protobuf:"bytes,1,opt,name=queries,proto3" json:"queries,omitempty"`
	Mutations     *structpb.Struct       `protobuf:"bytes,2,opt,name=mutations,proto3" json:"mutations,omitempty"`
	Subscriptions *structpb.Struct       `protobuf:"bytes,3,opt,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThirdPartyGraphQLSchemas) Reset() {
	*x = ThirdPartyGraphQLSchemas{}
	mi := &file_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThirdPartyGraphQLSchemas) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThirdPartyGraphQLSchemas) ProtoMessage() {}

func (x *ThirdPartyGraphQLSchemas) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThirdPartyGraphQLSchemas.ProtoReflect.Descriptor instead.
func (*ThirdPartyGraphQLSchemas) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *ThirdPartyGraphQLSchemas) GetQueries() *structpb.Struct {
	if x != nil {
		return x.Queries
	}
	return nil
}

func (x *ThirdPartyGraphQLSchemas) GetMutations() *structpb.Struct {
	if x != nil {
		return x.Mutations
	}
	return nil
}

func (x *ThirdPartyGraphQLSchemas) GetSubscriptions() *structpb.Struct {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

type ThirdPartyRESTApi struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Method      string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Path        string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Description string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Schema      *structpb.Struct       `protobuf:"bytes,4,opt,name=schema,proto3" json:"schema,omitempty"`
	// Optional: handler function name for this endpoint
	Handler       string `protobuf:"bytes,5,opt,name=handler,proto3" json:"handler,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThirdPartyRESTApi) Reset() {
	*x = ThirdPartyRESTApi{}
	mi := &file_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThirdPartyRESTApi) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThirdPartyRESTApi) ProtoMessage() {}

func (x *ThirdPartyRESTApi) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThirdPartyRESTApi.ProtoReflect.Descriptor instead.
func (*ThirdPartyRESTApi) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *ThirdPartyRESTApi) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *ThirdPartyRESTApi) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ThirdPartyRESTApi) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ThirdPartyRESTApi) GetSchema() *structpb.Struct {
	if x != nil {
		return x.Schema
	}
	return nil
}

func (x *ThirdPartyRESTApi) GetHandler() string {
	if x != nil {
		return x.Handler
	}
	return ""
}

type PluginProject struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Schema        *structpb.Struct       `protobuf:"bytes,4,opt,name=schema,proto3" json:"schema,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginProject) Reset() {
	*x = PluginProject{}
	mi := &file_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginProject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginProject) ProtoMessage() {}

func (x *PluginProject) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginProject.ProtoReflect.Descriptor instead.
func (*PluginProject) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *PluginProject) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PluginProject) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginProject) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PluginProject) GetSchema() *structpb.Struct {
	if x != nil {
		return x.Schema
	}
	return nil
}

func (x *PluginProject) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *PluginProject) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type AuditData struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Resource         string                 `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	Action           string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Author           *structpb.Struct       `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	Data             *structpb.Struct       `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	Meta             *structpb.Struct       `protobuf:"bytes,5,opt,name=meta,proto3" json:"meta,omitempty"`
	AdditionalFields *structpb.Struct       `protobuf:"bytes,6,opt,name=additional_fields,json=additionalFields,proto3" json:"additional_fields,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AuditData) Reset() {
	*x = AuditData{}
	mi := &file_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditData) ProtoMessage() {}

func (x *AuditData) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditData.ProtoReflect.Descriptor instead.
func (*AuditData) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *AuditData) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *AuditData) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AuditData) GetAuthor() *structpb.Struct {
	if x != nil {
		return x.Author
	}
	return nil
}

func (x *AuditData) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *AuditData) GetMeta() *structpb.Struct {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *AuditData) GetAdditionalFields() *structpb.Struct {
	if x != nil {
		return x.AdditionalFields
	}
	return nil
}

// Plugin Service Messages
type InitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnvVars       []*EnvVariable         `protobuf:"bytes,1,rep,name=env_vars,json=envVars,proto3" json:"env_vars,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitRequest) Reset() {
	*x = InitRequest{}
	mi := &file_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitRequest) ProtoMessage() {}

func (x *InitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitRequest.ProtoReflect.Descriptor instead.
func (*InitRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *InitRequest) GetEnvVars() []*EnvVariable {
	if x != nil {
		return x.EnvVars
	}
	return nil
}

type InitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitResponse) Reset() {
	*x = InitResponse{}
	mi := &file_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitResponse) ProtoMessage() {}

func (x *InitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitResponse.ProtoReflect.Descriptor instead.
func (*InitResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{8}
}

func (x *InitResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *InitResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type MigrationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MigrationRequest) Reset() {
	*x = MigrationRequest{}
	mi := &file_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MigrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrationRequest) ProtoMessage() {}

func (x *MigrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrationRequest.ProtoReflect.Descriptor instead.
func (*MigrationRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{9}
}

type MigrationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MigrationResponse) Reset() {
	*x = MigrationResponse{}
	mi := &file_plugin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MigrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrationResponse) ProtoMessage() {}

func (x *MigrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrationResponse.ProtoReflect.Descriptor instead.
func (*MigrationResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{10}
}

func (x *MigrationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MigrationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SchemaRegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchemaRegisterRequest) Reset() {
	*x = SchemaRegisterRequest{}
	mi := &file_plugin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchemaRegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchemaRegisterRequest) ProtoMessage() {}

func (x *SchemaRegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchemaRegisterRequest.ProtoReflect.Descriptor instead.
func (*SchemaRegisterRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{11}
}

type SchemaRegisterResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Schema        *ThirdPartyGraphQLSchemas `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchemaRegisterResponse) Reset() {
	*x = SchemaRegisterResponse{}
	mi := &file_plugin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchemaRegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchemaRegisterResponse) ProtoMessage() {}

func (x *SchemaRegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchemaRegisterResponse.ProtoReflect.Descriptor instead.
func (*SchemaRegisterResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{12}
}

func (x *SchemaRegisterResponse) GetSchema() *ThirdPartyGraphQLSchemas {
	if x != nil {
		return x.Schema
	}
	return nil
}

type RESTApiRegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RESTApiRegisterRequest) Reset() {
	*x = RESTApiRegisterRequest{}
	mi := &file_plugin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RESTApiRegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RESTApiRegisterRequest) ProtoMessage() {}

func (x *RESTApiRegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RESTApiRegisterRequest.ProtoReflect.Descriptor instead.
func (*RESTApiRegisterRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{13}
}

type RESTApiRegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Apis          []*ThirdPartyRESTApi   `protobuf:"bytes,1,rep,name=apis,proto3" json:"apis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RESTApiRegisterResponse) Reset() {
	*x = RESTApiRegisterResponse{}
	mi := &file_plugin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RESTApiRegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RESTApiRegisterResponse) ProtoMessage() {}

func (x *RESTApiRegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RESTApiRegisterResponse.ProtoReflect.Descriptor instead.
func (*RESTApiRegisterResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{14}
}

func (x *RESTApiRegisterResponse) GetApis() []*ThirdPartyRESTApi {
	if x != nil {
		return x.Apis
	}
	return nil
}

type GetVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVersionRequest) Reset() {
	*x = GetVersionRequest{}
	mi := &file_plugin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionRequest) ProtoMessage() {}

func (x *GetVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersionRequest.ProtoReflect.Descriptor instead.
func (*GetVersionRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{15}
}

type GetVersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVersionResponse) Reset() {
	*x = GetVersionResponse{}
	mi := &file_plugin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionResponse) ProtoMessage() {}

func (x *GetVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersionResponse.ProtoReflect.Descriptor instead.
func (*GetVersionResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{16}
}

func (x *GetVersionResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type ExecuteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FunctionName  string                 `protobuf:"bytes,1,opt,name=function_name,json=functionName,proto3" json:"function_name,omitempty"` // The function/resolver name to execute
	FunctionType  string                 `protobuf:"bytes,2,opt,name=function_type,json=functionType,proto3" json:"function_type,omitempty"` // Type: "graphql_query", "graphql_mutation", "rest_api", "function"
	Args          *structpb.Struct       `protobuf:"bytes,3,opt,name=args,proto3" json:"args,omitempty"`                                     // Arguments for the function
	Context       *structpb.Struct       `protobuf:"bytes,4,opt,name=context,proto3" json:"context,omitempty"`                               // Additional context data
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_plugin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{17}
}

func (x *ExecuteRequest) GetFunctionName() string {
	if x != nil {
		return x.FunctionName
	}
	return ""
}

func (x *ExecuteRequest) GetFunctionType() string {
	if x != nil {
		return x.FunctionType
	}
	return ""
}

func (x *ExecuteRequest) GetArgs() *structpb.Struct {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ExecuteRequest) GetContext() *structpb.Struct {
	if x != nil {
		return x.Context
	}
	return nil
}

type ExecuteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Result        *anypb.Any             `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"` // The actual result data
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_plugin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{18}
}

func (x *ExecuteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ExecuteResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ExecuteResponse) GetResult() *anypb.Any {
	if x != nil {
		return x.Result
	}
	return nil
}

// Host Service Messages
type GenerateTenantTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateTenantTokenRequest) Reset() {
	*x = GenerateTenantTokenRequest{}
	mi := &file_plugin_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateTenantTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateTenantTokenRequest) ProtoMessage() {}

func (x *GenerateTenantTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateTenantTokenRequest.ProtoReflect.Descriptor instead.
func (*GenerateTenantTokenRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{19}
}

func (x *GenerateTenantTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *GenerateTenantTokenRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type GenerateTenantTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateTenantTokenResponse) Reset() {
	*x = GenerateTenantTokenResponse{}
	mi := &file_plugin_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateTenantTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateTenantTokenResponse) ProtoMessage() {}

func (x *GenerateTenantTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateTenantTokenResponse.ProtoReflect.Descriptor instead.
func (*GenerateTenantTokenResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{20}
}

func (x *GenerateTenantTokenResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type GetProjectDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProjectDetailsRequest) Reset() {
	*x = GetProjectDetailsRequest{}
	mi := &file_plugin_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectDetailsRequest) ProtoMessage() {}

func (x *GetProjectDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectDetailsRequest.ProtoReflect.Descriptor instead.
func (*GetProjectDetailsRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{21}
}

func (x *GetProjectDetailsRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type GetProjectDetailsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       *PluginProject         `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProjectDetailsResponse) Reset() {
	*x = GetProjectDetailsResponse{}
	mi := &file_plugin_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectDetailsResponse) ProtoMessage() {}

func (x *GetProjectDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectDetailsResponse.ProtoReflect.Descriptor instead.
func (*GetProjectDetailsResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{22}
}

func (x *GetProjectDetailsResponse) GetProject() *PluginProject {
	if x != nil {
		return x.Project
	}
	return nil
}

type GetSingleResourceRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Model          string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Id             string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	SinglePageData bool                   `protobuf:"varint,3,opt,name=single_page_data,json=singlePageData,proto3" json:"single_page_data,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetSingleResourceRequest) Reset() {
	*x = GetSingleResourceRequest{}
	mi := &file_plugin_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSingleResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSingleResourceRequest) ProtoMessage() {}

func (x *GetSingleResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSingleResourceRequest.ProtoReflect.Descriptor instead.
func (*GetSingleResourceRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{23}
}

func (x *GetSingleResourceRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *GetSingleResourceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetSingleResourceRequest) GetSinglePageData() bool {
	if x != nil {
		return x.SinglePageData
	}
	return false
}

type GetSingleResourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      *anypb.Any             `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSingleResourceResponse) Reset() {
	*x = GetSingleResourceResponse{}
	mi := &file_plugin_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSingleResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSingleResourceResponse) ProtoMessage() {}

func (x *GetSingleResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSingleResourceResponse.ProtoReflect.Descriptor instead.
func (*GetSingleResourceResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{24}
}

func (x *GetSingleResourceResponse) GetResource() *anypb.Any {
	if x != nil {
		return x.Resource
	}
	return nil
}

type SearchResourcesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Filter        *structpb.Struct       `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	Aggregate     bool                   `protobuf:"varint,3,opt,name=aggregate,proto3" json:"aggregate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResourcesRequest) Reset() {
	*x = SearchResourcesRequest{}
	mi := &file_plugin_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResourcesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResourcesRequest) ProtoMessage() {}

func (x *SearchResourcesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResourcesRequest.ProtoReflect.Descriptor instead.
func (*SearchResourcesRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{25}
}

func (x *SearchResourcesRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *SearchResourcesRequest) GetFilter() *structpb.Struct {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *SearchResourcesRequest) GetAggregate() bool {
	if x != nil {
		return x.Aggregate
	}
	return false
}

type SearchResourcesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resources     *anypb.Any             `protobuf:"bytes,1,opt,name=resources,proto3" json:"resources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResourcesResponse) Reset() {
	*x = SearchResourcesResponse{}
	mi := &file_plugin_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResourcesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResourcesResponse) ProtoMessage() {}

func (x *SearchResourcesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResourcesResponse.ProtoReflect.Descriptor instead.
func (*SearchResourcesResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{26}
}

func (x *SearchResourcesResponse) GetResources() *anypb.Any {
	if x != nil {
		return x.Resources
	}
	return nil
}

type GetRelationDocumentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Connection    *structpb.Struct       `protobuf:"bytes,2,opt,name=connection,proto3" json:"connection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRelationDocumentsRequest) Reset() {
	*x = GetRelationDocumentsRequest{}
	mi := &file_plugin_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRelationDocumentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRelationDocumentsRequest) ProtoMessage() {}

func (x *GetRelationDocumentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRelationDocumentsRequest.ProtoReflect.Descriptor instead.
func (*GetRelationDocumentsRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{27}
}

func (x *GetRelationDocumentsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetRelationDocumentsRequest) GetConnection() *structpb.Struct {
	if x != nil {
		return x.Connection
	}
	return nil
}

type GetRelationDocumentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Documents     *anypb.Any             `protobuf:"bytes,1,opt,name=documents,proto3" json:"documents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRelationDocumentsResponse) Reset() {
	*x = GetRelationDocumentsResponse{}
	mi := &file_plugin_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRelationDocumentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRelationDocumentsResponse) ProtoMessage() {}

func (x *GetRelationDocumentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRelationDocumentsResponse.ProtoReflect.Descriptor instead.
func (*GetRelationDocumentsResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{28}
}

func (x *GetRelationDocumentsResponse) GetDocuments() *anypb.Any {
	if x != nil {
		return x.Documents
	}
	return nil
}

type CreateNewResourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Data          *structpb.Struct       `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Connection    *structpb.Struct       `protobuf:"bytes,3,opt,name=connection,proto3" json:"connection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNewResourceRequest) Reset() {
	*x = CreateNewResourceRequest{}
	mi := &file_plugin_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNewResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNewResourceRequest) ProtoMessage() {}

func (x *CreateNewResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNewResourceRequest.ProtoReflect.Descriptor instead.
func (*CreateNewResourceRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{29}
}

func (x *CreateNewResourceRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *CreateNewResourceRequest) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *CreateNewResourceRequest) GetConnection() *structpb.Struct {
	if x != nil {
		return x.Connection
	}
	return nil
}

type CreateNewResourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      *anypb.Any             `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNewResourceResponse) Reset() {
	*x = CreateNewResourceResponse{}
	mi := &file_plugin_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNewResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNewResourceResponse) ProtoMessage() {}

func (x *CreateNewResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNewResourceResponse.ProtoReflect.Descriptor instead.
func (*CreateNewResourceResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{30}
}

func (x *CreateNewResourceResponse) GetResource() *anypb.Any {
	if x != nil {
		return x.Resource
	}
	return nil
}

type UpdateResourceRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Model          string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Id             string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	SinglePageData bool                   `protobuf:"varint,3,opt,name=single_page_data,json=singlePageData,proto3" json:"single_page_data,omitempty"`
	Data           *structpb.Struct       `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	Connect        *structpb.Struct       `protobuf:"bytes,5,opt,name=connect,proto3" json:"connect,omitempty"`
	Disconnect     *structpb.Struct       `protobuf:"bytes,6,opt,name=disconnect,proto3" json:"disconnect,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateResourceRequest) Reset() {
	*x = UpdateResourceRequest{}
	mi := &file_plugin_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResourceRequest) ProtoMessage() {}

func (x *UpdateResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResourceRequest.ProtoReflect.Descriptor instead.
func (*UpdateResourceRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{31}
}

func (x *UpdateResourceRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *UpdateResourceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateResourceRequest) GetSinglePageData() bool {
	if x != nil {
		return x.SinglePageData
	}
	return false
}

func (x *UpdateResourceRequest) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UpdateResourceRequest) GetConnect() *structpb.Struct {
	if x != nil {
		return x.Connect
	}
	return nil
}

func (x *UpdateResourceRequest) GetDisconnect() *structpb.Struct {
	if x != nil {
		return x.Disconnect
	}
	return nil
}

type UpdateResourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      *anypb.Any             `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResourceResponse) Reset() {
	*x = UpdateResourceResponse{}
	mi := &file_plugin_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResourceResponse) ProtoMessage() {}

func (x *UpdateResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResourceResponse.ProtoReflect.Descriptor instead.
func (*UpdateResourceResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{32}
}

func (x *UpdateResourceResponse) GetResource() *anypb.Any {
	if x != nil {
		return x.Resource
	}
	return nil
}

type DeleteResourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResourceRequest) Reset() {
	*x = DeleteResourceRequest{}
	mi := &file_plugin_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResourceRequest) ProtoMessage() {}

func (x *DeleteResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResourceRequest.ProtoReflect.Descriptor instead.
func (*DeleteResourceRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{33}
}

func (x *DeleteResourceRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *DeleteResourceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteResourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResourceResponse) Reset() {
	*x = DeleteResourceResponse{}
	mi := &file_plugin_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResourceResponse) ProtoMessage() {}

func (x *DeleteResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResourceResponse.ProtoReflect.Descriptor instead.
func (*DeleteResourceResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{34}
}

func (x *DeleteResourceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteResourceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DebugRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stage         string                 `protobuf:"bytes,1,opt,name=stage,proto3" json:"stage,omitempty"`
	Data          []*anypb.Any           `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DebugRequest) Reset() {
	*x = DebugRequest{}
	mi := &file_plugin_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebugRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebugRequest) ProtoMessage() {}

func (x *DebugRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebugRequest.ProtoReflect.Descriptor instead.
func (*DebugRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{35}
}

func (x *DebugRequest) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

func (x *DebugRequest) GetData() []*anypb.Any {
	if x != nil {
		return x.Data
	}
	return nil
}

type DebugResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *anypb.Any             `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DebugResponse) Reset() {
	*x = DebugResponse{}
	mi := &file_plugin_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebugResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebugResponse) ProtoMessage() {}

func (x *DebugResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebugResponse.ProtoReflect.Descriptor instead.
func (*DebugResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{36}
}

func (x *DebugResponse) GetResult() *anypb.Any {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_plugin_proto protoreflect.FileDescriptor

const file_plugin_proto_rawDesc = "" +
	"\n" +
	"\fplugin.proto\x12\x0fapito.plugin.v1\x1a\x19google/protobuf/any.proto\x1a\x1cgoogle/protobuf/struct.proto\"f\n" +
	"\vEnvVariable\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x12\n" +
	"\x04hide\x18\x03 \x01(\bR\x04hide\x12\x1b\n" +
	"\tis_system\x18\x04 \x01(\bR\bisSystem\"\x9d\x01\n" +
	"\x18HashiCorpHandshakeConfig\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12(\n" +
	"\x10magic_cookie_key\x18\x02 \x01(\tR\x0emagicCookieKey\x12,\n" +
	"\x12magic_cookie_value\x18\x03 \x01(\tR\x10magicCookieValue\"\x82\a\n" +
	"\rPluginDetails\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04icon\x18\x03 \x01(\tR\x04icon\x12\x16\n" +
	"\x06serial\x18\x04 \x01(\x03R\x06serial\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12;\n" +
	"\bcategory\x18\a \x01(\x0e2\x1f.apito.plugin.v1.PluginCategoryR\bcategory\x12/\n" +
	"\x04type\x18\b \x01(\x0e2\x1b.apito.plugin.v1.PluginTypeR\x04type\x12\x12\n" +
	"\x04role\x18\t \x01(\tR\x04role\x127\n" +
	"\benv_vars\x18\n" +
	" \x03(\v2\x1c.apito.plugin.v1.EnvVariableR\aenvVars\x12+\n" +
	"\x11exported_variable\x18\v \x01(\tR\x10exportedVariable\x12\x16\n" +
	"\x06enable\x18\f \x01(\bR\x06enable\x12\x14\n" +
	"\x05debug\x18\r \x01(\bR\x05debug\x12%\n" +
	"\x0erepository_url\x18\x0e \x01(\tR\rrepositoryUrl\x12\x16\n" +
	"\x06branch\x18\x0f \x01(\tR\x06branch\x12\x16\n" +
	"\x06author\x18\x10 \x01(\tR\x06author\x12B\n" +
	"\vload_status\x18\x11 \x01(\x0e2!.apito.plugin.v1.PluginLoadStatusR\n" +
	"loadStatus\x12N\n" +
	"\x0factivate_status\x18\x12 \x01(\x0e2%.apito.plugin.v1.PluginActivateStatusR\x0eactivateStatus\x12.\n" +
	"\x13belongs_to_projects\x18\x13 \x03(\tR\x11belongsToProjects\x12\x1f\n" +
	"\vbinary_path\x18\x14 \x01(\tR\n" +
	"binaryPath\x12T\n" +
	"\x10handshake_config\x18\x15 \x01(\v2).apito.plugin.v1.HashiCorpHandshakeConfigR\x0fhandshakeConfig\x12;\n" +
	"\blanguage\x18\x16 \x01(\x0e2\x1f.apito.plugin.v1.PluginLanguageR\blanguage\"\xc3\x01\n" +
	"\x18ThirdPartyGraphQLSchemas\x121\n" +
	"\aqueries\x18\x01 \x01(\v2\x17.google.protobuf.StructR\aqueries\x125\n" +
	"\tmutations\x18\x02 \x01(\v2\x17.google.protobuf.StructR\tmutations\x12=\n" +
	"\rsubscriptions\x18\x03 \x01(\v2\x17.google.protobuf.StructR\rsubscriptions\"\xac\x01\n" +
	"\x11ThirdPartyRESTApi\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12/\n" +
	"\x06schema\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x06schema\x12\x18\n" +
	"\ahandler\x18\x05 \x01(\tR\ahandler\"\xc4\x01\n" +
	"\rPluginProject\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12/\n" +
	"\x06schema\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x06schema\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\"\x90\x02\n" +
	"\tAuditData\x12\x1a\n" +
	"\bresource\x18\x01 \x01(\tR\bresource\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12/\n" +
	"\x06author\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x06author\x12+\n" +
	"\x04data\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x04data\x12+\n" +
	"\x04meta\x18\x05 \x01(\v2\x17.google.protobuf.StructR\x04meta\x12D\n" +
	"\x11additional_fields\x18\x06 \x01(\v2\x17.google.protobuf.StructR\x10additionalFields\"F\n" +
	"\vInitRequest\x127\n" +
	"\benv_vars\x18\x01 \x03(\v2\x1c.apito.plugin.v1.EnvVariableR\aenvVars\"B\n" +
	"\fInitResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x12\n" +
	"\x10MigrationRequest\"G\n" +
	"\x11MigrationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x17\n" +
	"\x15SchemaRegisterRequest\"[\n" +
	"\x16SchemaRegisterResponse\x12A\n" +
	"\x06schema\x18\x01 \x01(\v2).apito.plugin.v1.ThirdPartyGraphQLSchemasR\x06schema\"\x18\n" +
	"\x16RESTApiRegisterRequest\"Q\n" +
	"\x17RESTApiRegisterResponse\x126\n" +
	"\x04apis\x18\x01 \x03(\v2\".apito.plugin.v1.ThirdPartyRESTApiR\x04apis\"\x13\n" +
	"\x11GetVersionRequest\".\n" +
	"\x12GetVersionResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\"\xba\x01\n" +
	"\x0eExecuteRequest\x12#\n" +
	"\rfunction_name\x18\x01 \x01(\tR\ffunctionName\x12#\n" +
	"\rfunction_type\x18\x02 \x01(\tR\ffunctionType\x12+\n" +
	"\x04args\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x04args\x121\n" +
	"\acontext\x18\x04 \x01(\v2\x17.google.protobuf.StructR\acontext\"s\n" +
	"\x0fExecuteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12,\n" +
	"\x06result\x18\x03 \x01(\v2\x14.google.protobuf.AnyR\x06result\"O\n" +
	"\x1aGenerateTenantTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\"3\n" +
	"\x1bGenerateTenantTokenResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"9\n" +
	"\x18GetProjectDetailsRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\"U\n" +
	"\x19GetProjectDetailsResponse\x128\n" +
	"\aproject\x18\x01 \x01(\v2\x1e.apito.plugin.v1.PluginProjectR\aproject\"j\n" +
	"\x18GetSingleResourceRequest\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12(\n" +
	"\x10single_page_data\x18\x03 \x01(\bR\x0esinglePageData\"M\n" +
	"\x19GetSingleResourceResponse\x120\n" +
	"\bresource\x18\x01 \x01(\v2\x14.google.protobuf.AnyR\bresource\"}\n" +
	"\x16SearchResourcesRequest\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12/\n" +
	"\x06filter\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x06filter\x12\x1c\n" +
	"\taggregate\x18\x03 \x01(\bR\taggregate\"M\n" +
	"\x17SearchResourcesResponse\x122\n" +
	"\tresources\x18\x01 \x01(\v2\x14.google.protobuf.AnyR\tresources\"f\n" +
	"\x1bGetRelationDocumentsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x127\n" +
	"\n" +
	"connection\x18\x02 \x01(\v2\x17.google.protobuf.StructR\n" +
	"connection\"R\n" +
	"\x1cGetRelationDocumentsResponse\x122\n" +
	"\tdocuments\x18\x01 \x01(\v2\x14.google.protobuf.AnyR\tdocuments\"\x96\x01\n" +
	"\x18CreateNewResourceRequest\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12+\n" +
	"\x04data\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x04data\x127\n" +
	"\n" +
	"connection\x18\x03 \x01(\v2\x17.google.protobuf.StructR\n" +
	"connection\"M\n" +
	"\x19CreateNewResourceResponse\x120\n" +
	"\bresource\x18\x01 \x01(\v2\x14.google.protobuf.AnyR\bresource\"\x80\x02\n" +
	"\x15UpdateResourceRequest\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12(\n" +
	"\x10single_page_data\x18\x03 \x01(\bR\x0esinglePageData\x12+\n" +
	"\x04data\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x04data\x121\n" +
	"\aconnect\x18\x05 \x01(\v2\x17.google.protobuf.StructR\aconnect\x127\n" +
	"\n" +
	"disconnect\x18\x06 \x01(\v2\x17.google.protobuf.StructR\n" +
	"disconnect\"J\n" +
	"\x16UpdateResourceResponse\x120\n" +
	"\bresource\x18\x01 \x01(\v2\x14.google.protobuf.AnyR\bresource\"=\n" +
	"\x15DeleteResourceRequest\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"L\n" +
	"\x16DeleteResourceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"N\n" +
	"\fDebugRequest\x12\x14\n" +
	"\x05stage\x18\x01 \x01(\tR\x05stage\x12(\n" +
	"\x04data\x18\x02 \x03(\v2\x14.google.protobuf.AnyR\x04data\"=\n" +
	"\rDebugResponse\x12,\n" +
	"\x06result\x18\x01 \x01(\v2\x14.google.protobuf.AnyR\x06result*g\n" +
	"\x0ePluginCategory\x12\x1a\n" +
	"\x16PLUGIN_CATEGORY_NORMAL\x10\x00\x12\x1c\n" +
	"\x18PLUGIN_CATEGORY_FUNCTION\x10\x01\x12\x1b\n" +
	"\x17PLUGIN_CATEGORY_STORAGE\x10\x02*@\n" +
	"\n" +
	"PluginType\x12\x18\n" +
	"\x14PLUGIN_TYPE_INTERNAL\x10\x00\x12\x18\n" +
	"\x14PLUGIN_TYPE_EXTERNAL\x10\x01*\xdf\x01\n" +
	"\x10PluginLoadStatus\x12$\n" +
	" PLUGIN_LOAD_STATUS_NOT_INSTALLED\x10\x00\x12 \n" +
	"\x1cPLUGIN_LOAD_STATUS_INSTALLED\x10\x01\x12 \n" +
	"\x1cPLUGIN_LOAD_STATUS_REINSTALL\x10\x02\x12\x1e\n" +
	"\x1aPLUGIN_LOAD_STATUS_LOADING\x10\x03\x12\x1d\n" +
	"\x19PLUGIN_LOAD_STATUS_LOADED\x10\x04\x12\"\n" +
	"\x1ePLUGIN_LOAD_STATUS_LOAD_FAILED\x10\x05*d\n" +
	"\x14PluginActivateStatus\x12&\n" +
	"\"PLUGIN_ACTIVATE_STATUS_DEACTIVATED\x10\x00\x12$\n" +
	" PLUGIN_ACTIVATE_STATUS_ACTIVATED\x10\x01*\xcb\x02\n" +
	"\x0ePluginLanguage\x12\x16\n" +
	"\x12PLUGIN_LANGUAGE_GO\x10\x00\x12\x16\n" +
	"\x12PLUGIN_LANGUAGE_JS\x10\x01\x12\x17\n" +
	"\x13PLUGIN_LANGUAGE_CPP\x10\x02\x12\x1a\n" +
	"\x16PLUGIN_LANGUAGE_PYTHON\x10\x03\x12\x18\n" +
	"\x14PLUGIN_LANGUAGE_JAVA\x10\x04\x12\x18\n" +
	"\x14PLUGIN_LANGUAGE_RUBY\x10\x05\x12\x17\n" +
	"\x13PLUGIN_LANGUAGE_PHP\x10\x06\x12\x1a\n" +
	"\x16PLUGIN_LANGUAGE_CSHARP\x10\a\x12\x1e\n" +
	"\x1aPLUGIN_LANGUAGE_TYPESCRIPT\x10\b\x12\x18\n" +
	"\x14PLUGIN_LANGUAGE_RUST\x10\t\x12\x17\n" +
	"\x13PLUGIN_LANGUAGE_LUA\x10\n" +
	"\x12\x18\n" +
	"\x14PLUGIN_LANGUAGE_DART\x10\v2\x96\x04\n" +
	"\rPluginService\x12C\n" +
	"\x04Init\x12\x1c.apito.plugin.v1.InitRequest\x1a\x1d.apito.plugin.v1.InitResponse\x12R\n" +
	"\tMigration\x12!.apito.plugin.v1.MigrationRequest\x1a\".apito.plugin.v1.MigrationResponse\x12a\n" +
	"\x0eSchemaRegister\x12&.apito.plugin.v1.SchemaRegisterRequest\x1a'.apito.plugin.v1.SchemaRegisterResponse\x12d\n" +
	"\x0fRESTApiRegister\x12'.apito.plugin.v1.RESTApiRegisterRequest\x1a(.apito.plugin.v1.RESTApiRegisterResponse\x12U\n" +
	"\n" +
	"GetVersion\x12\".apito.plugin.v1.GetVersionRequest\x1a#.apito.plugin.v1.GetVersionResponse\x12L\n" +
	"\aExecute\x12\x1f.apito.plugin.v1.ExecuteRequest\x1a .apito.plugin.v1.ExecuteResponse2\xac\a\n" +
	"\vHostService\x12p\n" +
	"\x13GenerateTenantToken\x12+.apito.plugin.v1.GenerateTenantTokenRequest\x1a,.apito.plugin.v1.GenerateTenantTokenResponse\x12j\n" +
	"\x11GetProjectDetails\x12).apito.plugin.v1.GetProjectDetailsRequest\x1a*.apito.plugin.v1.GetProjectDetailsResponse\x12j\n" +
	"\x11GetSingleResource\x12).apito.plugin.v1.GetSingleResourceRequest\x1a*.apito.plugin.v1.GetSingleResourceResponse\x12d\n" +
	"\x0fSearchResources\x12'.apito.plugin.v1.SearchResourcesRequest\x1a(.apito.plugin.v1.SearchResourcesResponse\x12s\n" +
	"\x14GetRelationDocuments\x12,.apito.plugin.v1.GetRelationDocumentsRequest\x1a-.apito.plugin.v1.GetRelationDocumentsResponse\x12j\n" +
	"\x11CreateNewResource\x12).apito.plugin.v1.CreateNewResourceRequest\x1a*.apito.plugin.v1.CreateNewResourceResponse\x12a\n" +
	"\x0eUpdateResource\x12&.apito.plugin.v1.UpdateResourceRequest\x1a'.apito.plugin.v1.UpdateResourceResponse\x12a\n" +
	"\x0eDeleteResource\x12&.apito.plugin.v1.DeleteResourceRequest\x1a'.apito.plugin.v1.DeleteResourceResponse\x12F\n" +
	"\x05Debug\x12\x1d.apito.plugin.v1.DebugRequest\x1a\x1e.apito.plugin.v1.DebugResponseB\rZ\v./protobuffb\x06proto3"

var (
	file_plugin_proto_rawDescOnce sync.Once
	file_plugin_proto_rawDescData []byte
)

func file_plugin_proto_rawDescGZIP() []byte {
	file_plugin_proto_rawDescOnce.Do(func() {
		file_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_proto_rawDesc), len(file_plugin_proto_rawDesc)))
	})
	return file_plugin_proto_rawDescData
}

var file_plugin_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 37)
var file_plugin_proto_goTypes = []any{
	(PluginCategory)(0),                  // 0: apito.plugin.v1.PluginCategory
	(PluginType)(0),                      // 1: apito.plugin.v1.PluginType
	(PluginLoadStatus)(0),                // 2: apito.plugin.v1.PluginLoadStatus
	(PluginActivateStatus)(0),            // 3: apito.plugin.v1.PluginActivateStatus
	(PluginLanguage)(0),                  // 4: apito.plugin.v1.PluginLanguage
	(*EnvVariable)(nil),                  // 5: apito.plugin.v1.EnvVariable
	(*HashiCorpHandshakeConfig)(nil),     // 6: apito.plugin.v1.HashiCorpHandshakeConfig
	(*PluginDetails)(nil),                // 7: apito.plugin.v1.PluginDetails
	(*ThirdPartyGraphQLSchemas)(nil),     // 8: apito.plugin.v1.ThirdPartyGraphQLSchemas
	(*ThirdPartyRESTApi)(nil),            // 9: apito.plugin.v1.ThirdPartyRESTApi
	(*PluginProject)(nil),                // 10: apito.plugin.v1.PluginProject
	(*AuditData)(nil),                    // 11: apito.plugin.v1.AuditData
	(*InitRequest)(nil),                  // 12: apito.plugin.v1.InitRequest
	(*InitResponse)(nil),                 // 13: apito.plugin.v1.InitResponse
	(*MigrationRequest)(nil),             // 14: apito.plugin.v1.MigrationRequest
	(*MigrationResponse)(nil),            // 15: apito.plugin.v1.MigrationResponse
	(*SchemaRegisterRequest)(nil),        // 16: apito.plugin.v1.SchemaRegisterRequest
	(*SchemaRegisterResponse)(nil),       // 17: apito.plugin.v1.SchemaRegisterResponse
	(*RESTApiRegisterRequest)(nil),       // 18: apito.plugin.v1.RESTApiRegisterRequest
	(*RESTApiRegisterResponse)(nil),      // 19: apito.plugin.v1.RESTApiRegisterResponse
	(*GetVersionRequest)(nil),            // 20: apito.plugin.v1.GetVersionRequest
	(*GetVersionResponse)(nil),           // 21: apito.plugin.v1.GetVersionResponse
	(*ExecuteRequest)(nil),               // 22: apito.plugin.v1.ExecuteRequest
	(*ExecuteResponse)(nil),              // 23: apito.plugin.v1.ExecuteResponse
	(*GenerateTenantTokenRequest)(nil),   // 24: apito.plugin.v1.GenerateTenantTokenRequest
	(*GenerateTenantTokenResponse)(nil),  // 25: apito.plugin.v1.GenerateTenantTokenResponse
	(*GetProjectDetailsRequest)(nil),     // 26: apito.plugin.v1.GetProjectDetailsRequest
	(*GetProjectDetailsResponse)(nil),    // 27: apito.plugin.v1.GetProjectDetailsResponse
	(*GetSingleResourceRequest)(nil),     // 28: apito.plugin.v1.GetSingleResourceRequest
	(*GetSingleResourceResponse)(nil),    // 29: apito.plugin.v1.GetSingleResourceResponse
	(*SearchResourcesRequest)(nil),       // 30: apito.plugin.v1.SearchResourcesRequest
	(*SearchResourcesResponse)(nil),      // 31: apito.plugin.v1.SearchResourcesResponse
	(*GetRelationDocumentsRequest)(nil),  // 32: apito.plugin.v1.GetRelationDocumentsRequest
	(*GetRelationDocumentsResponse)(nil), // 33: apito.plugin.v1.GetRelationDocumentsResponse
	(*CreateNewResourceRequest)(nil),     // 34: apito.plugin.v1.CreateNewResourceRequest
	(*CreateNewResourceResponse)(nil),    // 35: apito.plugin.v1.CreateNewResourceResponse
	(*UpdateResourceRequest)(nil),        // 36: apito.plugin.v1.UpdateResourceRequest
	(*UpdateResourceResponse)(nil),       // 37: apito.plugin.v1.UpdateResourceResponse
	(*DeleteResourceRequest)(nil),        // 38: apito.plugin.v1.DeleteResourceRequest
	(*DeleteResourceResponse)(nil),       // 39: apito.plugin.v1.DeleteResourceResponse
	(*DebugRequest)(nil),                 // 40: apito.plugin.v1.DebugRequest
	(*DebugResponse)(nil),                // 41: apito.plugin.v1.DebugResponse
	(*structpb.Struct)(nil),              // 42: google.protobuf.Struct
	(*anypb.Any)(nil),                    // 43: google.protobuf.Any
}
var file_plugin_proto_depIdxs = []int32{
	0,  // 0: apito.plugin.v1.PluginDetails.category:type_name -> apito.plugin.v1.PluginCategory
	1,  // 1: apito.plugin.v1.PluginDetails.type:type_name -> apito.plugin.v1.PluginType
	5,  // 2: apito.plugin.v1.PluginDetails.env_vars:type_name -> apito.plugin.v1.EnvVariable
	2,  // 3: apito.plugin.v1.PluginDetails.load_status:type_name -> apito.plugin.v1.PluginLoadStatus
	3,  // 4: apito.plugin.v1.PluginDetails.activate_status:type_name -> apito.plugin.v1.PluginActivateStatus
	6,  // 5: apito.plugin.v1.PluginDetails.handshake_config:type_name -> apito.plugin.v1.HashiCorpHandshakeConfig
	4,  // 6: apito.plugin.v1.PluginDetails.language:type_name -> apito.plugin.v1.PluginLanguage
	42, // 7: apito.plugin.v1.ThirdPartyGraphQLSchemas.queries:type_name -> google.protobuf.Struct
	42, // 8: apito.plugin.v1.ThirdPartyGraphQLSchemas.mutations:type_name -> google.protobuf.Struct
	42, // 9: apito.plugin.v1.ThirdPartyGraphQLSchemas.subscriptions:type_name -> google.protobuf.Struct
	42, // 10: apito.plugin.v1.ThirdPartyRESTApi.schema:type_name -> google.protobuf.Struct
	42, // 11: apito.plugin.v1.PluginProject.schema:type_name -> google.protobuf.Struct
	42, // 12: apito.plugin.v1.AuditData.author:type_name -> google.protobuf.Struct
	42, // 13: apito.plugin.v1.AuditData.data:type_name -> google.protobuf.Struct
	42, // 14: apito.plugin.v1.AuditData.meta:type_name -> google.protobuf.Struct
	42, // 15: apito.plugin.v1.AuditData.additional_fields:type_name -> google.protobuf.Struct
	5,  // 16: apito.plugin.v1.InitRequest.env_vars:type_name -> apito.plugin.v1.EnvVariable
	8,  // 17: apito.plugin.v1.SchemaRegisterResponse.schema:type_name -> apito.plugin.v1.ThirdPartyGraphQLSchemas
	9,  // 18: apito.plugin.v1.RESTApiRegisterResponse.apis:type_name -> apito.plugin.v1.ThirdPartyRESTApi
	42, // 19: apito.plugin.v1.ExecuteRequest.args:type_name -> google.protobuf.Struct
	42, // 20: apito.plugin.v1.ExecuteRequest.context:type_name -> google.protobuf.Struct
	43, // 21: apito.plugin.v1.ExecuteResponse.result:type_name -> google.protobuf.Any
	10, // 22: apito.plugin.v1.GetProjectDetailsResponse.project:type_name -> apito.plugin.v1.PluginProject
	43, // 23: apito.plugin.v1.GetSingleResourceResponse.resource:type_name -> google.protobuf.Any
	42, // 24: apito.plugin.v1.SearchResourcesRequest.filter:type_name -> google.protobuf.Struct
	43, // 25: apito.plugin.v1.SearchResourcesResponse.resources:type_name -> google.protobuf.Any
	42, // 26: apito.plugin.v1.GetRelationDocumentsRequest.connection:type_name -> google.protobuf.Struct
	43, // 27: apito.plugin.v1.GetRelationDocumentsResponse.documents:type_name -> google.protobuf.Any
	42, // 28: apito.plugin.v1.CreateNewResourceRequest.data:type_name -> google.protobuf.Struct
	42, // 29: apito.plugin.v1.CreateNewResourceRequest.connection:type_name -> google.protobuf.Struct
	43, // 30: apito.plugin.v1.CreateNewResourceResponse.resource:type_name -> google.protobuf.Any
	42, // 31: apito.plugin.v1.UpdateResourceRequest.data:type_name -> google.protobuf.Struct
	42, // 32: apito.plugin.v1.UpdateResourceRequest.connect:type_name -> google.protobuf.Struct
	42, // 33: apito.plugin.v1.UpdateResourceRequest.disconnect:type_name -> google.protobuf.Struct
	43, // 34: apito.plugin.v1.UpdateResourceResponse.resource:type_name -> google.protobuf.Any
	43, // 35: apito.plugin.v1.DebugRequest.data:type_name -> google.protobuf.Any
	43, // 36: apito.plugin.v1.DebugResponse.result:type_name -> google.protobuf.Any
	12, // 37: apito.plugin.v1.PluginService.Init:input_type -> apito.plugin.v1.InitRequest
	14, // 38: apito.plugin.v1.PluginService.Migration:input_type -> apito.plugin.v1.MigrationRequest
	16, // 39: apito.plugin.v1.PluginService.SchemaRegister:input_type -> apito.plugin.v1.SchemaRegisterRequest
	18, // 40: apito.plugin.v1.PluginService.RESTApiRegister:input_type -> apito.plugin.v1.RESTApiRegisterRequest
	20, // 41: apito.plugin.v1.PluginService.GetVersion:input_type -> apito.plugin.v1.GetVersionRequest
	22, // 42: apito.plugin.v1.PluginService.Execute:input_type -> apito.plugin.v1.ExecuteRequest
	24, // 43: apito.plugin.v1.HostService.GenerateTenantToken:input_type -> apito.plugin.v1.GenerateTenantTokenRequest
	26, // 44: apito.plugin.v1.HostService.GetProjectDetails:input_type -> apito.plugin.v1.GetProjectDetailsRequest
	28, // 45: apito.plugin.v1.HostService.GetSingleResource:input_type -> apito.plugin.v1.GetSingleResourceRequest
	30, // 46: apito.plugin.v1.HostService.SearchResources:input_type -> apito.plugin.v1.SearchResourcesRequest
	32, // 47: apito.plugin.v1.HostService.GetRelationDocuments:input_type -> apito.plugin.v1.GetRelationDocumentsRequest
	34, // 48: apito.plugin.v1.HostService.CreateNewResource:input_type -> apito.plugin.v1.CreateNewResourceRequest
	36, // 49: apito.plugin.v1.HostService.UpdateResource:input_type -> apito.plugin.v1.UpdateResourceRequest
	38, // 50: apito.plugin.v1.HostService.DeleteResource:input_type -> apito.plugin.v1.DeleteResourceRequest
	40, // 51: apito.plugin.v1.HostService.Debug:input_type -> apito.plugin.v1.DebugRequest
	13, // 52: apito.plugin.v1.PluginService.Init:output_type -> apito.plugin.v1.InitResponse
	15, // 53: apito.plugin.v1.PluginService.Migration:output_type -> apito.plugin.v1.MigrationResponse
	17, // 54: apito.plugin.v1.PluginService.SchemaRegister:output_type -> apito.plugin.v1.SchemaRegisterResponse
	19, // 55: apito.plugin.v1.PluginService.RESTApiRegister:output_type -> apito.plugin.v1.RESTApiRegisterResponse
	21, // 56: apito.plugin.v1.PluginService.GetVersion:output_type -> apito.plugin.v1.GetVersionResponse
	23, // 57: apito.plugin.v1.PluginService.Execute:output_type -> apito.plugin.v1.ExecuteResponse
	25, // 58: apito.plugin.v1.HostService.GenerateTenantToken:output_type -> apito.plugin.v1.GenerateTenantTokenResponse
	27, // 59: apito.plugin.v1.HostService.GetProjectDetails:output_type -> apito.plugin.v1.GetProjectDetailsResponse
	29, // 60: apito.plugin.v1.HostService.GetSingleResource:output_type -> apito.plugin.v1.GetSingleResourceResponse
	31, // 61: apito.plugin.v1.HostService.SearchResources:output_type -> apito.plugin.v1.SearchResourcesResponse
	33, // 62: apito.plugin.v1.HostService.GetRelationDocuments:output_type -> apito.plugin.v1.GetRelationDocumentsResponse
	35, // 63: apito.plugin.v1.HostService.CreateNewResource:output_type -> apito.plugin.v1.CreateNewResourceResponse
	37, // 64: apito.plugin.v1.HostService.UpdateResource:output_type -> apito.plugin.v1.UpdateResourceResponse
	39, // 65: apito.plugin.v1.HostService.DeleteResource:output_type -> apito.plugin.v1.DeleteResourceResponse
	41, // 66: apito.plugin.v1.HostService.Debug:output_type -> apito.plugin.v1.DebugResponse
	52, // [52:67] is the sub-list for method output_type
	37, // [37:52] is the sub-list for method input_type
	37, // [37:37] is the sub-list for extension type_name
	37, // [37:37] is the sub-list for extension extendee
	0,  // [0:37] is the sub-list for field type_name
}

func init() { file_plugin_proto_init() }
func file_plugin_proto_init() {
	if File_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_proto_rawDesc), len(file_plugin_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   37,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_plugin_proto_goTypes,
		DependencyIndexes: file_plugin_proto_depIdxs,
		EnumInfos:         file_plugin_proto_enumTypes,
		MessageInfos:      file_plugin_proto_msgTypes,
	}.Build()
	File_plugin_proto = out.File
	file_plugin_proto_goTypes = nil
	file_plugin_proto_depIdxs = nil
}
